### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by kands-code** [gaowanliang/googleTranslatorKusaMaker#2]
当我装好依赖运行main.py时，界面能够正常显示，但是翻译出错，显示返回失败，终端报错如下：

```
Traceback (most recent call last):
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/main.py", line 33, in translate
    if translator.detect(raw).lang != "zh-CN":
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/googletrans/client.py", line 249, in detect
    data = self._translate(text, dest='en', src='auto')
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/googletrans/gtoken.py", line 200, in do
    self._update()
  File "/home/kands/Downloads/googleTranslatorKusaMaker-master/lib/python3.9/site-packages/googletrans/gtoken.py", line 65, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by gaowanliang** [comment]
建议用 python3.6版本，高版本可能导致不可预知的问题
